### ISSUE TITLE
python 3 is not supported

### ISSUE THREAD

**Issue by petacube** [StatisKit/AutoWIG#54]
please upgrade to support python 3 pref 3.5-3.6 with anaconda

**Comment by pfernique** [comment]
In order to benefit from all **AutoWIG**'s functionalities, **ClangLite** (`libclanglite` & `python-clanglite`) must be installed.
Unfortunately, building `libclanglite` and `python-clanglite` requires **SCons** that does not yet support *Python 3*.

Nevertheless, generating wrappers for *C++*/*Python 3* is still possible using an environment with *Python 2* to write wrappers with **AutoWIG** and to compile these wrappers in another environment with *Python 3*.

Note that until this issue, *Python 2* wasn't forced in **Conda** recipes.
So if you have installed **Conda 3**, it's quite possible that this could induce some problems such as the one presented in the issue #53.
This have been changed but it could take some time to be uploaded to **StatisKit** channel.

**Comment by xantares** [comment]
what if we have the clang python bindings instead of clanglite (out of anaconda) ? autowig seems to be working. (at least it produces cpp files), then autowig still doesnt support running on py3k (the first error I see is related to basestring).

**Comment by pfernique** [comment]
If you install **AutoWIG** from source code, one solution could be to use the following command
```bash
2to3 -w src/py/autowig test/
```
before the installation.

If not, let me know, I will try to produce *Python 3* binaries for **AutoWIG** and its dependencies (except **ClangLite**).

**Comment by petacube** [comment]
i am very interested in collaboration in making its python 3 compatible
Pierre, what the complexity with clanglite?

**Comment by pfernique** [comment]
The complexity is with **SCons**.
**SCons** is a *Python* program used to compile the *C++* code.
Unfortunately, **SCons** is written in *Python 2* and not in *Python 3*.
**Scons** developers are planning to support *Python 3*, but when ?
I tried to use **enscons** that extend **SCons** for building *Python* packages with **SCons** and that is written in *Python 3* (more information on this [site](https://bitbucket.org/dholth/enscons)).
Nevertheless, only **SCons** tools related to *Python* packages seemed to have been tested and the compilation of *C++* code failed.

**Comment by petacube** [comment]
Pierre, have you heard of clif?
https://github.com/google/clif <https://github.com/google/clif>

**Comment by pfernique** [comment]
Didn't know **clif**.
Quite busy right know, I will take a look later after [EuroSciPy](https://www.euroscipy.org/2017).

**Comment by pfernique** [comment]
Good news, everyone !

Using the **SCons 3.0.0-alpha** version supporting *Python 3*, I succeed to produce binaries for *Python 3.6* for **AutoWIG** and **ClangLite** (available on Anaconda Cloud).
I only tested the Linux systems with the unit tests.
I will try on OsX and Windows during this week.

**Comment by pfernique** [comment]
Tests passed on Ubuntu, OsX and Windows (32bit).
I'm closing down this issue.
