### ISSUE TITLE
Are you considering publishing wheels on pypi?

### ISSUE THREAD

**Issue by virtuald** [StatisKit/AutoWIG#64]
This project is really cool. It's [very similar to the autogenerator I've been trying to create](https://github.com/robotpy/robotpy-build) for the RobotPy project, but this considerably more comprehensive at the present moment.

A primary problem I have with it (and I suspect others might also) is that I don't use conda at all, and I'm not really interested in doing so for a variety of reasons. I tried using [conda-press](https://github.com/regro/conda-press) to make this into a wheel, but the result was quite ugly.

It would be great if one could just do 'pip install autowig' and have it work. Is that on the roadmap for this project?

**Comment by pfernique** [comment]
The problem with using pip is the following:
To be functional AutoWIG requires ClangLite (a mininal set of wrappers using PyBind11 (or Boost.Python for previous versions) of Clang/LLVM to produce ASTs  generated by a previous version of AutoWIG) that requires LLVM and Clang compiled with RTTI (not a standard way to compile them). 
I'm not really familiar with PIP but I think it is mostly used for Python packages not C/C++ libraries.
One solution is to generate wrappers using the conda installation. Then, you are free to compile the wrappers on any machine (normally) that doesn't use Conda.

**Comment by brupelo** [comment]
Interesting project, just found this project while I was looking for llvm's python wrappers in order to replace some of my good old automatic wrapper generators using CppHeaderParser :)

I do agree with @virtuald , while the underlying idea & backend used by this project are really cool I think not giving the users an easy way to install it with `pip install autowig` is a major mistake. Why? Because not many people won't use your cool stuff :)

There is something I really don't understand... after reading this [paper](https://peerj.com/articles/cs-149.pdf) you guys claim the goal of this project is making life of scientists easier... and yet you're forcing them to use conda and managing all prerequisites by themselves? I don't get it

Anyway, I'll be keeping an eye how this project evolves but I won't try it till it becomes user-friendly. And yeah... not everyone uses conda ;)

Ns. Don't get me wrong, I'm not criticizing just giving feedback... I think this project has a lot of potential. Few months ago I'd considered using [llvmlite](https://llvmlite.readthedocs.io/en/latest/) to do something similar

**Comment by virtuald** [comment]
@brupelo I'd encourage you to check out [robotpy-build](https://github.com/robotpy/robotpy-build) which uses an improved fork of CppHeaderParser ... there's limited documentation at the moment (probably will do this in the coming weeks), but I've used it to successfully wrap several very large C++11/17 libraries.

**Comment by brupelo** [comment]
@virtuald Oh, thanks, I'm a really passionate about python wraper generators and I wasn't aware of that one, I'll take a look.

Speaking of which, is `CppHeaderParser` still being developed? I thought it had been abandoned/archived. Few years ago I had to use it in some projects to wrap a large Qt library into sip and unfortunately I had to keep a private fork with some tweaks because I thought it wasn't still being developed any longer. If it's still being developed and trying to support c++ >=11 I'd gladly use it & contribute to it.

Btw, how difficult would be to generate wrapper of some of my projects using robotpy-build on windows?

**Comment by virtuald** [comment]
CppHeaderParser does appear to be abandoned by the original author (for good reason -- its code is a mess!), so we forked it as [robotpy-cppheaderparser](https://github.com/robotpy/robotpy-cppheaderparser).

We use robotpy-build to autowrap on Linux, OSX, and Windows. I haven't publicized it more because the documentation is mostly non-existent -- but feel free to stop by our gitter at https://gitter.im/robotpy/robotpy-wpilib with questions. A good example repo to start with is [robotpy-adi](https://github.com/robotpy/robotpy-adi).

**Comment by brupelo** [comment]
@virtuald Oh, really cool stuff, thanks... in the coming weeks I'll definitely find some time to start using your nicer fork (the code definitely looks much nicer than the good old one), I also see it's pypi installable :laughing: and I see you guys accept PRs... all of them are good reasons to consider contributing. I recall I'd had to give support to some specific Qt stuff and guess you wouldn't mind new PRs if those would just extend existing functionality, right?

Anyway, I'll definitely be giving it a shot as well to robotpy-wpilib to see how fast you can wrap stuff, looks really promising ;)
